python optim.py manifold_hybrid bathroom
python optim.py manifold_caustic cornellbox
python optim.py manifold_hybrid shadow
python optim.py manifold highlight
python optim.py manifold bedroom
python optim.py manifold bunny
python optim.py manifold glossyball
python optim.py manifold_caustic egg
python optim.py manifold glassslab
python optim.py manifold human